version: "3.9"

services:
  bot-prod:
    build: .
    command: python main.py
    env_file:
      - .env.prod.example
    volumes:
      - ./content/cache/prod:/app/content/cache/prod

  bot-sandbox:
    build: .
    command: python main.py
    env_file:
      - .env.sandbox.example
    volumes:
      - ./content/cache/sandbox:/app/content/cache/sandbox
